package ru.otr.lbss.client.model.exceptions;

import ru.otr.lbss.client.model.types.fault.DestinationOverflow;

import javax.xml.ws.WebFault;


/**
 * 
 *                     Очередь, в которую должен быть послано сообщение, переполнена.
 *                     Действия клиента: обратиться в службу техподдержки СМЭВ, и продолжать посылать запрос повторно, до успеха.
 *                 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DestinationOverflow", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.3")
public class DestinationOverflowException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DestinationOverflow faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DestinationOverflowException(String message, DestinationOverflow faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DestinationOverflowException(String message, DestinationOverflow faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.otr.lbss.client.model.DestinationOverflow
     */
    public DestinationOverflow getFaultInfo() {
        return faultInfo;
    }

}
