
package ru.otr.lbss.client.model.exceptions;

import javax.xml.ws.WebFault;

import ru.otr.lbss.client.model.types.basic.Void;

/**
 * 
 * Сообщение с таким MessageID уже было отправлено ранее. Возможно в следующих
 * ситуациях: a) Клиент пытался отправить сообщение, отправка прошла успешно, но
 * в конце взаимодействия HTTP соединение оборвалось, и клиент не получил ответ
 * от СМЭВ об успешной отправке. При повторной попытке отправить сообщение
 * клиент получит этот fault. В этой ситуации нужно прекратить пытаться повторно
 * послать сообщение. b) Клиент использует алгоритм генерации ID сообщений, не
 * соответствующий МР. c) Клиент пытается послать несколько сообщений, используя
 * один и тот же ID.
 * 
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MessageIsAlreadySent", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")
public class MessageIsAlreadySentException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3167691084047955764L;
	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private Void faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public MessageIsAlreadySentException(String message, Void faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public MessageIsAlreadySentException(String message, Void faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         ru.it.smev.message_exchange.autogenerated.types.basic.v1_1.Void
	 */
	public Void getFaultInfo() {
		return faultInfo;
	}

}
