package ru.otr.lbss.client.model.exceptions;

import ru.otr.lbss.client.model.types.fault.QuoteLimitExceeded;

import javax.xml.ws.WebFault;


/**
 * 
 *                     Суммарный размер вложений превысил значения квоты СМЭВ.
 *                 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "QuoteLimitExceeded", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.3")
public class QuoteLimitExceededException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private QuoteLimitExceeded faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public QuoteLimitExceededException(String message, QuoteLimitExceeded faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public QuoteLimitExceededException(String message, QuoteLimitExceeded faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.otr.lbss.client.model.QuoteLimitExceeded
     */
    public QuoteLimitExceeded getFaultInfo() {
        return faultInfo;
    }

}
