package ru.otr.lbss.client.model.exceptions;

import ru.otr.lbss.client.model.types.fault.SignatureVerificationFault;

import javax.xml.ws.WebFault;


/**
 * 
 *                     ЭП-ОВ не прошла проверку.
 *                     Действия клиента: см. описание {urn://x-artefacts-smev-gov-ru/smev-core/client-interaction/types/1.3}SignatureVerificationFault.
 *                 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SignatureVerificationFault", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.3")
public class SignatureVerificationFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SignatureVerificationFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SignatureVerificationFaultException(String message, SignatureVerificationFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SignatureVerificationFaultException(String message, SignatureVerificationFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.otr.lbss.client.model.SignatureVerificationFault
     */
    public SignatureVerificationFault getFaultInfo() {
        return faultInfo;
    }

}
