package ru.otr.lbss.client.model.exceptions;

import ru.otr.lbss.client.model.types.basic.SmevFault;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TransactionCodeInvalid", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.3")
public class TransactionCodeInvalidException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SmevFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TransactionCodeInvalidException(String message, SmevFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TransactionCodeInvalidException(String message, SmevFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.otr.lbss.client.model.SmevFault
     */
    public SmevFault getFaultInfo() {
        return faultInfo;
    }

}
