
package ru.otr.lbss.ws.api.exceptions;

import javax.xml.ws.WebFault;

import ru.otr.lbss.ws.api.types.fault.DestinationOverflow;

/**
 * 
 * Очередь, в которую должен быть послано сообщение, переполнена. Действия
 * клиента: обратиться в службу техподдержки СМЭВ, и продолжать посылать запрос
 * повторно, до успеха.
 * 
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DestinationOverflow", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")
public class DestinationOverflowException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6072555297472348567L;
	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private DestinationOverflow faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public DestinationOverflowException(String message, DestinationOverflow faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public DestinationOverflowException(String message, DestinationOverflow faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         ru.it.smev.message_exchange.autogenerated.types.fault.v1_1.
	 *         DestinationOverflow
	 */
	public DestinationOverflow getFaultInfo() {
		return faultInfo;
	}

}
