
package ru.otr.lbss.ws.api.exceptions;

import javax.xml.ws.WebFault;

import ru.otr.lbss.ws.api.types.basic.Void;

/**
 * 
 * Идентификатор (UUID), присвоенный сообщению отправителем, содержит старый
 * timestamp. Возможно в следующих случаях: a) в системе отправителя неверно
 * установлено время. Действия клиента: установить в операционной системе
 * реальное время. b) в результате очень плохого качества связи, сообщение
 * пытаются отправить в течение двух суток или более. Действия клиента:
 * сгенерировать новый UUID, присвоить его сообщению, отправить сообщение.
 * 
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "StaleMessageId", targetNamespace = "urn://x-artefacts-smev-gov-ru/services/message-exchange/types/faults/1.1")
public class StaleMessageIdException extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1398749162112351357L;
	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private Void faultInfo;

	/**
	 * 
	 * @param faultInfo
	 * @param message
	 */
	public StaleMessageIdException(String message, Void faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param faultInfo
	 * @param cause
	 * @param message
	 */
	public StaleMessageIdException(String message, Void faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         ru.it.smev.message_exchange.autogenerated.types.basic.v1_1.Void
	 */
	public Void getFaultInfo() {
		return faultInfo;
	}

}
