
package com.otr.sufd.smev30supportservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "smev30SupportService", targetNamespace = "http://www.otr.com/sufd/smev30SupportService", wsdlLocation = "file:/media/sf_public/ws/smev30Support.wsdl")
public class Smev30SupportService extends Service {
    private static Logger log = LoggerFactory.getLogger(Smev30SupportService.class);

    private final static URL SMEV30SUPPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMEV30SUPPORTSERVICE_EXCEPTION;
    private final static QName SMEV30SUPPORTSERVICE_QNAME = new QName("http://www.otr.com/sufd/smev30SupportService", "smev30SupportService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = Smev30SupportService.class.getResource("/META-INF/wsdl/smev30Support.wsdl");
            log.info("WSDL Location: " + url);
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        SMEV30SUPPORTSERVICE_WSDL_LOCATION = url;
        SMEV30SUPPORTSERVICE_EXCEPTION = e;
    }

    public Smev30SupportService() {
        super(__getWsdlLocation(), SMEV30SUPPORTSERVICE_QNAME);
    }

    public Smev30SupportService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMEV30SUPPORTSERVICE_QNAME, features);
    }

    public Smev30SupportService(URL wsdlLocation) {
        super(wsdlLocation, SMEV30SUPPORTSERVICE_QNAME);
    }

    public Smev30SupportService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMEV30SUPPORTSERVICE_QNAME, features);
    }

    public Smev30SupportService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Smev30SupportService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return returns Smev30SupportServicePortType
     */
    @WebEndpoint(name = "smev30SupportServicePort")
    public Smev30SupportServicePortType getSmev30SupportServicePort() {
        return super.getPort(new QName("http://www.otr.com/sufd/smev30SupportService", "smev30SupportServicePort"), Smev30SupportServicePortType.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns Smev30SupportServicePortType
     */
    @WebEndpoint(name = "smev30SupportServicePort")
    public Smev30SupportServicePortType getSmev30SupportServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.otr.com/sufd/smev30SupportService", "smev30SupportServicePort"), Smev30SupportServicePortType.class,
                features);
    }

    private static URL __getWsdlLocation() {
        if (SMEV30SUPPORTSERVICE_EXCEPTION != null) {
            throw SMEV30SUPPORTSERVICE_EXCEPTION;
        }
        return SMEV30SUPPORTSERVICE_WSDL_LOCATION;
    }

}
