
package ru.otr.lbss.ws.api.types.basic;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * ru.it.smev.message_exchange.autogenerated.types.basic.v1_1 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * ru.it.smev.message_exchange.autogenerated.types.basic.v1_1
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Timestamp }
	 * 
	 */
	public Timestamp createTimestamp() {
		return new Timestamp();
	}

	/**
	 * Create an instance of {@link XMLDSigSignatureType }
	 * 
	 */
	public XMLDSigSignatureType createXMLDSigSignatureType() {
		return new XMLDSigSignatureType();
	}

	/**
	 * Create an instance of {@link SmevFault }
	 * 
	 */
	public SmevFault createSmevFault() {
		return new SmevFault();
	}

	/**
	 * Create an instance of {@link MessageReference }
	 * 
	 */
	public MessageReference createMessageReference() {
		return new MessageReference();
	}

	/**
	 * Create an instance of {@link AckTargetMessage }
	 * 
	 */
	public AckTargetMessage createAckTargetMessage() {
		return new AckTargetMessage();
	}

	/**
	 * Create an instance of {@link MessagePrimaryContent }
	 * 
	 */
	public MessagePrimaryContent createMessagePrimaryContent() {
		return new MessagePrimaryContent();
	}

	/**
	 * Create an instance of {@link AttachmentHeaderList }
	 * 
	 */
	public AttachmentHeaderList createAttachmentHeaderList() {
		return new AttachmentHeaderList();
	}

	/**
	 * Create an instance of {@link AttachmentHeaderType }
	 * 
	 */
	public AttachmentHeaderType createAttachmentHeaderType() {
		return new AttachmentHeaderType();
	}

	/**
	 * Create an instance of {@link RefAttachmentHeaderList }
	 * 
	 */
	public RefAttachmentHeaderList createRefAttachmentHeaderList() {
		return new RefAttachmentHeaderList();
	}

	/**
	 * Create an instance of {@link RefAttachmentHeaderType }
	 * 
	 */
	public RefAttachmentHeaderType createRefAttachmentHeaderType() {
		return new RefAttachmentHeaderType();
	}

	/**
	 * Create an instance of {@link Void }
	 * 
	 */
	public Void createVoid() {
		return new Void();
	}

	/**
	 * Create an instance of {@link FSAttachmentsList }
	 * 
	 */
	public FSAttachmentsList createFSAttachmentsList() {
		return new FSAttachmentsList();
	}

	/**
	 * Create an instance of {@link FSAuthInfo }
	 * 
	 */
	public FSAuthInfo createFSAuthInfo() {
		return new FSAuthInfo();
	}

	/**
	 * Create an instance of {@link AttachmentContentList }
	 * 
	 */
	public AttachmentContentList createAttachmentContentList() {
		return new AttachmentContentList();
	}

	/**
	 * Create an instance of {@link AttachmentContentType }
	 * 
	 */
	public AttachmentContentType createAttachmentContentType() {
		return new AttachmentContentType();
	}

	/**
	 * Create an instance of {@link MessageTypeSelector }
	 * 
	 */
	public MessageTypeSelector createMessageTypeSelector() {
		return new MessageTypeSelector();
	}

}
